parameters:
    dna_complements:
        A: T
        T: A
        G: C
        C: G
    codons:
        Alanine:
            1: 'A'
            3: 'Ala'
        Aspartate_or_asparagine:
            1: 'B'
        Cysteine:
            1: 'C'
            3: 'Cys'
        Aspartic_acid:
            1: 'D'
            3: 'Asp'
        Glutamic_acid:
            1: 'E'
            3: 'Glu'
        Phenylalanine:
            1: 'F'
            3: 'Phe'
        Glycine:
            1: 'G'
            3: 'Gly'
        Histidine:
            1: 'H'
            3: 'His'
        Isoleucine:
            1: 'I'
            3: 'Ile'
        Lysine:
            1: 'K'
            3: 'Lys'
        Leucine:
            1: 'L'
            3: 'Leu'
        Methionine:
            1: 'M'
            3: 'Met'
        Asparagine:
            1: 'N'
            3: 'Asn'
        Proline:
            1: 'P'
            3: 'Pro'
        Glutamine:
            1: 'Q'
            3: 'Gin'
        Arginine:
            1: 'R'
            3: 'Arg'
        Serine:
            1: 'S'
            3: 'Ser'
        Threonine:
            1: 'T'
            3: 'Thr'
        Selenocysteine:
            1: 'U'
            3: 'Sec'
        Valine:
            1: 'V'
            3: 'Val'
        Tryptophan:
            1: 'W'
            3: 'Trp'
        Tyrosine:
            1: 'Y'
            3: 'Tyr'
        Glutamate_or_glutamine:
            1: 'Z'
        Any:
            1: 'X'
            3: 'XXX'
        STOP:
            1: '*'
            3: 'STP'
    analysis_color:
        polar: 'magenta'
        nonpolar: 'yellow'
        charged: 'red'
        hydrophobic: 'green'
        positively_charged: 'blue'
        negatively_charged: 'red'
    nucleotids_graphs:
        positions_2:
          h_pos: 24
          v_pos: 26
        intervals_2: 64
        startx_2: 10
        starty_2: 90
        fcgr_file: 'FCGR.png'
        cgr_file: 'CGR.png'
        dendogram_file: 'dendogram.png'
        path_graphs: 'created_files/'