parameters:
    nucleotids_graphs:
        positions_2:
          h_pos: 24
          v_pos: 26
        intervals_2: 64
        startx_2: 10
        starty_2: 90
        fcgr_file: 'FCGR.png'
        cgr_file: 'CGR.png'
        dendogram_file: 'dendogram.png'
        path_graphs: 'created_files/'